import React from 'react'
import type { Metadata } from "next";
type Props = {}

export const metadata: Metadata = {
  title: "Day 1 | animatin name here",
  description: "Generated by create next app",
};
const page = (props: Props) => {
  return (
    <div>Challenge Number 1 </div>
  )
}

export default page;