import React from "react";
import type { Metadata } from "next";
import Day1TextFadeIn from "@/components/Day1TextFadeIn";
type Props = {};

export const metadata: Metadata = {
  title: "Day 1 | Fade In Effect for a text",
  description: "Generated by create next app",
};
const page = (props: Props) => {
  return (
    <section className="flex items-center justify-center min-h-screen">
      <Day1TextFadeIn />
    </section>
  );
};

export default page;
