import React from "react";

type Props = {};
import type { Metadata } from "next";
import Day8DrapAndDrop from "@/components/Day8DrapAndDrop";
export const metadata: Metadata = {
  title: "Day 8 | Drag and Drop animation",
  description: "Generated by create next app",
};

const DragAndDropAnimation = (props: Props) => {
  return (
    <div className="">
      <Day8DrapAndDrop />
    </div>
  );
};

export default DragAndDropAnimation;
