import React from 'react'
import type { Metadata } from "next";
type Props = {}

export const metadata: Metadata = {
  title: "Day 4 | animatin name here",
  description: "Generated by create next app",
};
const page = (props: Props) => {
  return (
    <div className='flex items-center justify-center min-h-screen px-5'>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores consequuntur laudantium rerum necessitatibus molestiae qui nemo magni, deleniti eos alias officia enim cupiditate. Nobis laborum ex nam voluptatum sed accusantium. Day 4
      </p>
    </div>
  )
}

export default page;