import React from "react";
import type { Metadata } from "next";
import Day4Spinner from "@/components/Day4Spinner";
type Props = {};

export const metadata: Metadata = {
  title: "Day 4 | Spinner Animation",
  description: "Generated by create next app",
};
const page = (props: Props) => {
  return (
    <div className="flex items-center justify-center min-h-screen px-5">
      <Day4Spinner />
    </div>
  );
};

export default page;
