import Day9SvgAnimation from "@/components/Day9SvgAnimation";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Day 9 | SVG Animation",
  description: "Generated by create next app",
};
type Props = {};

const SvgAnimation = (props: Props) => {
  return (
    <div className="flex items-center justify-center min-h-screen">
      <Day9SvgAnimation />
    </div>
  );
};

export default SvgAnimation;
