import Day6ProgressBar from "@/components/Day6ProgressBar";
import React from "react";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Day 6 | Progress bar animation",
  description: "Generated by create next app",
};
type Props = {};
const Day6ProgressBarPage = (props: Props) => {
  return (
    <div>
      <Day6ProgressBar />
    </div>
  );
};

export default Day6ProgressBarPage;
