import React from "react";
import type { Metadata } from "next";
import Day5Progress from "@/components/Day5Progress"
type Props = {};

export const metadata: Metadata = {
  title: "Day 5 | Fade In Animation",
  description: "Generated by create next app",
};
const page = (props: Props) => {
  return (
    <div className="">
      <Day5Progress />
    </div>
  );
};

export default page;
