import React from "react";

import { Metadata } from "next";
import Day10ExitAnimation from "@/components/Day10ExitAnimation";

export const metadata: Metadata = {
  title: "Day 10 | Exit Animation using AnimatePresence",
  description: "Generated by create next app",
};
const ExitAnimation = () => {
  return <div className="todobackground flex items-center justify-center min-h-screen ">
    <Day10ExitAnimation/>
  </div>;
};

export default ExitAnimation;
