import React from "react";
import type { Metadata } from "next";
import Day3Button from "@/components/Day3Button";
type Props = {};

export const metadata: Metadata = {
  title: "Day 3 | Button Animation with skill",
  description: "Generated by create next app",
};
const page = (props: Props) => {
  return (
    <div className="flex items-center justify-center min-h-screen px-5">
      <Day3Button />
    </div>
  );
};

export default page;
