import React from "react";

type Props = {};

import type { Metadata } from "next";
import Day7KeyFramerAnimation from "@/components/Day7KeyFramerAnimation";
export const metadata: Metadata = {
  title: "Day 7 | Keyframe animation",
  description: "Generated by create next app",
};

const KeyFramerAnimation = (props: Props) => {
  return <div>
    <Day7KeyFramerAnimation/>
  </div>;
};

export default KeyFramerAnimation;
