import React from "react";
import type { Metadata } from "next";
import Day2SlideIn from "@/components/Day2SlideIn";
type Props = {};

export const metadata: Metadata = {
  title: "Day 2 | Slide-in menu from the left.",
  description: "Generated by create next app",
};
const page = (props: Props) => {
  return (
    <>
      <section className="flex items-center justify-center min-h-screen">
        <Day2SlideIn />
      </section>
    </>
  );
};

export default page;
